local set = vim.opt

set.expandtab = true
set.smarttab = true
set.shiftwidth = 2
set.tabstop = 2
set.hlsearch = false
set.incsearch = true
set.ignorecase = true
set.smartcase = true
set.splitbelow = true
set.splitright = true
set.wrap = false
set.scrolloff = 8
set.sidescrolloff = 8
set.conceallevel = 2
set.termguicolors = true
set.relativenumber = true
-- set.number = true
set.cursorline = true
set.hidden = true
set.signcolumn = 'number'
set.clipboard = 'unnamed'
set.updatetime = 300
set.completeopt = 'menuone,noselect'
set.showmode = false
set.wildmenu = true
set.cursorline = false
set.encoding = 'utf-8'
set.fileencoding = 'utf-8'
set.fileencodings = 'utf-8,ucs-bom,gb18030,gbk,gb2312,cp936'
